# Generated by Django 5.2.8 on 2025-11-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_remove_user_roll_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('staff', 'staff'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
