# Generated by Django 5.2.8 on 2025-11-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsupport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('staff', 'staff')], default='user', max_length=20),
        ),
    ]
