# Generated by Django 5.2.8 on 2025-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_alter_ticketsupport_assigned_to_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsupport',
            name='department',
            field=models.CharField(blank=True, choices=[('support', 'support'), ('technical', 'technical'), ('sells', 'sells')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketsupport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
