# Generated by Django 5.2.8 on 2025-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_ticketsupport_department_ticketsupport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super admin'), ('user', 'user'), ('staff', 'staff')], default='user', max_length=20),
        ),
    ]
