# Generated by Django 5.2.8 on 2025-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('user', 'user'), ('staff', 'staff')], default='user', max_length=20),
        ),
    ]
